name: powder_pool
description: "A Flutter App for Skiers and Snowboarders to travel together"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/resorts/
    - assets/images/pros/

dependencies:
  flutter:
    sdk: flutter
  async: 2.12.0
  flutter_riverpod: 2.3.6
  riverpod: 2.3.6
  freezed_annotation: 2.4.4
  go_router: 13.2.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  uuid: ^4.5.1
  intl: ^0.18.1
  getwidget: ^6.0.0
  responsive_grid: ^2.4.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^2.4.5
  json_serializable: ^6.1.1

  flutter_lints: ^5.0.0