name: powder_pool
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/resorts/
    - assets/images/pros/

dependencies:
  flutter:
    sdk: flutter
  async: 2.12.0
  flutter_riverpod: 2.3.6
  riverpod: 2.3.6
  freezed_annotation: 2.4.4
  go_router: 13.2.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0